import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/Nikosh.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/Nikosh.woff2",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const ptSerif = localFont({
  src: "./fonts/PTSerif-Regular.ttf",
  weight: "400",
  style: "normal",
  variable: "--font-pt-serif",
});
// const ptSerif = localFont({
//   src: "./fonts/PTSerif-Regular.woff2",
//   weight: "400",
//   style: "normal",
//   variable: "--font-pt-serif",
// });

export const metadata = {
  title: "- Apostille",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ptSerif.variable} antialiased`}
      >
        <Toaster position="top-center" reverseOrder={false} />
        {children}
      </body>
    </html>
  );
}
